language: python

python:
  - "2.7"
  - "3.4"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -q -n pyenv python=$TRAVIS_PYTHON_VERSION pip numpy scipy cython matplotlib scikit-learn nose pyyaml
  - source activate pyenv
  - pip install -q git+https://github.com/Theano/Theano.git@rel-0.7
  - pip install -q argparse
  - pip install -e git+https://github.com/lisa-lab/pylearn2.git#egg=pylearn2

script:
  - nosetests -v sknn
